In [1]:
!pip install pandas
!pip install openpyxl

import pandas as pd 
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\12500739\appdata\roaming\python\python312\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\12500739\appdata\roaming\python\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\12500739\appdata\roaming\python\python312\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\12500739\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\12500739\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)

In [23]:
caminho = r"H:\Python\3°-Etapa\Atividade_4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [24]:
tabela_populacao = pd.read_excel(caminho, header = 2)

In [25]:
tabela_populacao

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
tabela_populacao = tabela_populacao.iloc[ 1:5570, 1:]

In [31]:
tabela_populacao["diferenca"] = tabela_populacao["População Censo 2022"] - tabela_populacao["População Município 2010\n(Sinopse)"]

In [34]:
tabela_populacao.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferenca'],
      dtype='str')

In [35]:
uf_populacao = (tabela_populacao.groupby("UF")[['População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferenca']]).sum().reset_index()

In [43]:
uf_populacao.sort_values(by='UF', ascending=True)

,UF,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferenca
0,AC,733559.0,733559.0,830018.0,96459.0
1,AL,3120494.0,3120887.0,3127683.0,7189.0
2,AM,3483985.0,3483985.0,3941613.0,457628.0
3,AP,669526.0,669526.0,733759.0,64233.0
4,BA,14016906.0,14017071.0,14141626.0,124720.0
5,CE,8452381.0,8451644.0,8794957.0,342576.0
6,DF,2570160.0,2572159.0,2817381.0,247221.0
7,ES,3514952.0,3514952.0,3833712.0,318760.0
8,GO,6003788.0,6001789.0,7056495.0,1052707.0
9,MA,6574789.0,6574789.0,6776699.0,201910.0
10,MG,19597330.0,19597330.0,20539989.0,942659.0
11,MS,2449024.0,2449024.0,2757013.0,307989.0
12,MT,3035122.0,3035122.0,3658649.0,623527.0
13,PA,7581051.0,7581051.0,8120131.0,539080.0
14,PB,3766528.0,3766528.0,3974687.0,208159.0
15,PE,8796448.0,8796055.0,9058931.0,262483.0
16,PI,3118360.0,3119097.0,3271199.0,152839.0
17,PR,10444526.0,10444526.0,11444380.0,999854.0
18,RJ,15989929.0,15989929.0,16055174.0,65245.0
19,RN,3168027.0,3168027.0,3302729.0,134702.0
20,RO,1538017.0,1538017.0,1559702.0,21685.0
21,RR,450479.0,450479.0,636707.0,186228.0
22,RS,10693929.0,10693929.0,10882965.0,189036.0
23,SC,6248436.0,6248436.0,7610361.0,1361925.0
24,SE,2068017.0,2067852.0,2210004.0,141987.0
25,SP,41262199.0,41262199.0,44411238.0,3149039.0
26,TO,1383445.0,1383445.0,1511460.0,128015.0

In [44]:
uf_populacao.to_csv(r"H:\Python\3°-Etapa\Atividade_4\uf_populacao.csv", sep =";")

In [45]:
muni_populacao = (tabela_populacao.groupby("NOME DO MUNICÍPIO")[['População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferenca']]).sum().reset_index()

In [47]:
muni_populacao.sort_values(by='NOME DO MUNICÍPIO', ascending=True)

,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferenca
0,Abadia de Goiás,6876.0,6891.0,19128.0,12252.0
1,Abadia dos Dourados,6704.0,6704.0,6272.0,-432.0
2,Abadiânia,15757.0,15759.0,17232.0,1475.0
3,Abaetetuba,141100.0,141100.0,158188.0,17088.0
4,Abaeté,22690.0,22690.0,22675.0,-15.0
...,...,...,...,...,...
5291,Áurea,3665.0,3665.0,3396.0,-269.0
5292,Ângulo,2859.0,2859.0,3235.0,376.0
5293,Érico Cardoso,10859.0,10882.0,10604.0,-255.0
5294,Óbidos,49333.0,49333.0,52229.0,2896.0
5295,Óleo,2673.0,2673.0,2512.0,-161.0

In [48]:
muni_populacao.to_csv(r"H:\Python\3°-Etapa\Atividade_4\muni_populacao.csv", sep =";")